### ISSUE TITLE
Issue with MTTU Calculation When No Releases Are Found.

### ISSUE THREAD

**Issue by BrenoFariasdaSilva** [HckEX/AutoMetric#1]
### Problem Description
The current implementation of the Mean Time to Update (MTTU) calculation fails to provide a meaningful output when there are no releases in the repository. This can lead to a situation where the MTTU is reported as "n/a" without considering the available tag dates, which can still provide valuable insights into the update frequency of the project.

### Fork and Modifications
I have made a fork of the project and significantly modified the codebase to improve code quality, add execution arguments, and enhance documentation. Additionally, I addressed the issue with MTTU computation by implementing a solution that calculates the MTTU using the dates of tags when no releases are found.

You can see how I computed the MTTU with tags in this commit: [Commit 457aea41](https://github.com/BrenoFariasdaSilva/AutoMetric/commit/457aea41f6493e3a7279982c4dc9bb36fef13758).

If you're interested, I can create a pull request for my fork. However, please be aware that it would be a significant PR due to the extensive changes made. Let me know if you'd like me to proceed with that!

**Comment by lee-taejun** [comment]
Hi, sorry for the delayed response.

At the time of development, we considered release information to be the most accurate data for the MTTU calculation, and we designed the process with the expectation that MTTC would handle cases where no releases were found. However, after reviewing the issue and looking into the tag information across several projects, I agree that utilizing tag dates for the MTTU when no releases are available is a reasonable and valuable approach.

I’ve reviewed the commit you provided, and I would be happy if you could submit a PR. Thanks a lot for the effort you've put into this!

**Comment by BrenoFariasdaSilva** [comment]
Pull Request Sent [here](https://github.com/HckEX/AutoMetric/pull/2)! :)

**Comment by lee-taejun** [comment]
@BrenoFariasdaSilva Thank you for your contribution. I recently returned from military service, which is why it took some time to approve the pull request. The PR has now been merged, and I’ll close this issue.
